export { default as Landing } from './Landing/Landing'
export { default as Login } from './Auth/Login/Login'
export { default as Register } from './Auth/Register/Register'
// Admin
export { default as AdminDashboard } from './AdminDashboard/Dashboard'
export { default as AdminEvents } from './AdminEvents/Events'
export { default as AdminSchedule } from './AdminSchedule/Schedule'
export { default as AdminAttendance } from './AdminAttendance/Attendance'
export { default as AdminPenalties } from './AdminPenalties/Penalties'
export { default as AdminUsers } from './AdminUsers/Users'
export { default as AdminTransaction } from './AdminTransaction/Transaction'
export { default as AdminProject } from './AdminProject/ProjectPage'
export { default as AdminItem } from './AdminItem/Item'
export { default as AdminCollection } from './AdminCollection/Collection'
export { default as AdminReport } from './AdminReport/AdminReport'
export { default as AdminClearance } from './AdminClearance/Clearance'
export { default as AdminSchoolYear } from './AdminSchoolYear/SchoolYear'
export { default as AdminSignatories } from './AdminSignatories/Signatories'
// User
export { default as UserDashboard } from './UserDashboard/Dashboard'
export { default as UserAttendance } from './UserAttendance/Attendance'
export { default as UserCollection } from './UserCollection/Collection'
export { default as UserTransaction } from './UserTransaction/Transaction'
export { default as UserClearance } from './UserClearance/UserClearance'